name: simple_dyphic
description: Simple Daily physical condition recording App.

publish_to: 'none'

version: 3.1.0+6

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  table_calendar: ^3.2.0
  health: ^13.1.4

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  google_sign_in: ^7.2.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1

  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
